import { Weapon, SavedResult, ProgramType } from './types.ts';

export const DEFAULT_WEAPONS: Weapon[] = [
  {
    id: 'w1',
    brand: 'Pardini',
    model: 'SP Rapid Fire',
    year: '2021',
    serialNumber: 'PAR-88291',
    boughtFrom: 'Børselars AS',
    lastServiceDate: '2026-03-15',
    shotsFired: 3450,
  },
  {
    id: 'w2',
    brand: 'Glock',
    model: '17 Gen 5 MOS',
    year: '2022',
    serialNumber: 'GLK-G5-9921',
    boughtFrom: 'Oslo Skytesenter',
    lastServiceDate: '2025-10-10',
    shotsFired: 1850,
  },
  {
    id: 'w3',
    brand: 'Sig Sauer',
    model: 'P210 Super Target',
    year: '2020',
    serialNumber: 'SIG-P210-994',
    boughtFrom: 'Våpen-Søilen',
    lastServiceDate: '2026-01-20',
    shotsFired: 950,
  },
];

export const DEFAULT_RESULTS: SavedResult[] = [
  {
    id: 'r1',
    date: '2026-04-10T14:30:00.000Z',
    programType: ProgramType.NAIS,
    weaponId: 'w2',
    weaponLabel: 'Glock 17 Gen 5 MOS',
    seriesCount: 6,
    series: [
      { name: '1. serie', timeLimit: 150, shots: ['9', '9', '8', '7', '10'], score: 43, innerTens: 0, isPractice: false },
      { name: '2. serie', timeLimit: 150, shots: ['10', '9', '9', '8', 'X'], score: 46, innerTens: 1, isPractice: false },
      { name: '3. serie (Duell)', timeLimit: 3, shots: ['9', '8', '8', '7', '6'], score: 38, innerTens: 0, isPractice: false },
      { name: '4. serie (Duell)', timeLimit: 3, shots: ['X', '10', '9', '8', '7'], score: 44, innerTens: 1, isPractice: false },
      { name: '5. serie', timeLimit: 20, shots: ['X', 'X', '9', '9', '8'], score: 46, innerTens: 2, isPractice: false },
      { name: '6. serie', timeLimit: 10, shots: ['9', '8', '8', '7', '5'], score: 37, innerTens: 0, isPractice: false },
    ],
    totalScore: 254,
    innerTensCount: 4,
  },
  {
    id: 'r2',
    date: '2026-04-28T18:00:00.000Z',
    programType: ProgramType.NAIS,
    weaponId: 'w2',
    weaponLabel: 'Glock 17 Gen 5 MOS',
    seriesCount: 6,
    series: [
      { name: '1. serie', timeLimit: 150, shots: ['10', '9', '9', '9', '8'], score: 45, innerTens: 0, isPractice: false },
      { name: '2. serie', timeLimit: 150, shots: ['X', '10', '9', '9', '8'], score: 46, innerTens: 1, isPractice: false },
      { name: '3. serie (Duell)', timeLimit: 3, shots: ['9', '9', '8', '8', '7'], score: 41, innerTens: 0, isPractice: false },
      { name: '4. serie (Duell)', timeLimit: 3, shots: ['10', '9', '9', '8', '8'], score: 44, innerTens: 0, isPractice: false },
      { name: '5. serie', timeLimit: 20, shots: ['X', '10', '10', '9', '7'], score: 46, innerTens: 1, isPractice: false },
      { name: '6. serie', timeLimit: 10, shots: ['10', '9', '8', '8', '8'], score: 43, innerTens: 0, isPractice: false },
    ],
    totalScore: 265,
    innerTensCount: 2,
  },
  {
    id: 'r3',
    date: '2026-05-15T15:20:00.000Z',
    programType: ProgramType.Hurtig,
    weaponId: 'w1',
    weaponLabel: 'Pardini SP Rapid Fire',
    seriesCount: 12,
    series: [
      { name: '1. serie', timeLimit: 10, shots: ['10', '10', '9', '9', '8'], score: 46, innerTens: 0, isPractice: false },
      { name: '2. serie', timeLimit: 10, shots: ['X', '9', '9', '8', '8'], score: 44, innerTens: 1, isPractice: false },
      { name: '3. serie', timeLimit: 10, shots: ['X', 'X', '10', '9', '9'], score: 48, innerTens: 2, isPractice: false },
      { name: '4. serie', timeLimit: 10, shots: ['10', '9', '9', '9', '8'], score: 45, innerTens: 0, isPractice: false },
      { name: '5. serie', timeLimit: 8, shots: ['X', '10', '9', '8', '8'], score: 45, innerTens: 1, isPractice: false },
      { name: '6. serie', timeLimit: 8, shots: ['10', '9', '9', '8', '7'], score: 43, innerTens: 0, isPractice: false },
      { name: '7. serie', timeLimit: 8, shots: ['10', '10', '9', '8', '8'], score: 45, innerTens: 0, isPractice: false },
      { name: '8. serie', timeLimit: 8, shots: ['X', 'X', '10', '9', '9'], score: 48, innerTens: 2, isPractice: false },
      { name: '9. serie', timeLimit: 6, shots: ['10', '9', '8', '7', '7'], score: 41, innerTens: 0, isPractice: false },
      { name: '10. serie', timeLimit: 6, shots: ['9', '9', '8', '8', '7'], score: 41, innerTens: 0, isPractice: false },
      { name: '11. serie', timeLimit: 6, shots: ['10', '9', '9', '8', '8'], score: 44, innerTens: 0, isPractice: false },
      { name: '12. serie', timeLimit: 6, shots: ['X', '10', '9', '9', '8'], score: 46, innerTens: 1, isPractice: false },
    ],
    totalScore: 541,
    innerTensCount: 7,
  },
  {
    id: 'r4',
    date: '2026-06-02T19:15:00.000Z',
    programType: ProgramType.Hurtig,
    weaponId: 'w1',
    weaponLabel: 'Pardini SP Rapid Fire',
    seriesCount: 12,
    series: [
      { name: '1. serie', timeLimit: 10, shots: ['10', '10', '10', '9', '9'], score: 48, innerTens: 0, isPractice: false },
      { name: '2. serie', timeLimit: 10, shots: ['X', 'X', '9', '9', '9'], score: 47, innerTens: 2, isPractice: false },
      { name: '3. serie', timeLimit: 10, shots: ['X', '10', '10', '9', '8'], score: 47, innerTens: 1, isPractice: false },
      { name: '4. serie', timeLimit: 10, shots: ['10', '9', '9', '9', '9'], score: 46, innerTens: 0, isPractice: false },
      { name: '5. serie', timeLimit: 8, shots: ['X', 'X', '10', '9', '8'], score: 47, innerTens: 2, isPractice: false },
      { name: '6. serie', timeLimit: 8, shots: ['X', '10', '9', '9', '9'], score: 47, innerTens: 1, isPractice: false },
      { name: '7. serie', timeLimit: 8, shots: ['X', '10', '10', '9', '8'], score: 47, innerTens: 1, isPractice: false },
      { name: '8. serie', timeLimit: 8, shots: ['10', '10', '9', '9', '9'], score: 47, innerTens: 0, isPractice: false },
      { name: '9. serie', timeLimit: 6, shots: ['X', '9', '9', '8', '8'], score: 44, innerTens: 1, isPractice: false },
      { name: '10. serie', timeLimit: 6, shots: ['10', '10', '9', '8', '8'], score: 45, innerTens: 0, isPractice: false },
      { name: '11. serie', timeLimit: 6, shots: ['X', '10', '9', '9', '8'], score: 46, innerTens: 1, isPractice: false },
      { name: '12. serie', timeLimit: 6, shots: ['10', '9', '9', '9', '8'], score: 45, innerTens: 0, isPractice: false },
    ],
    totalScore: 556,
    innerTensCount: 9,
  },
  {
    id: 'r5',
    date: '2026-05-01T10:00:00.000Z',
    programType: ProgramType.Standardpistol,
    weaponId: 'w3',
    weaponLabel: 'Sig Sauer P210 Super Target',
    seriesCount: 12,
    series: [
      { name: '1. serie', timeLimit: 150, shots: ['10', '10', '9', '9', '9'], score: 47, innerTens: 0, isPractice: false },
      { name: '2. serie', timeLimit: 150, shots: ['X', '9', '9', '9', '8'], score: 45, innerTens: 1, isPractice: false },
      { name: '3. serie', timeLimit: 150, shots: ['X', '10', '10', '9', '9'], score: 48, innerTens: 1, isPractice: false },
      { name: '4. serie', timeLimit: 150, shots: ['10', '10', '9', '9', '8'], score: 46, innerTens: 0, isPractice: false },
      { name: '5. serie', timeLimit: 20, shots: ['9', '9', '9', '8', '8'], score: 43, innerTens: 0, isPractice: false },
      { name: '6. serie', timeLimit: 20, shots: ['X', '9', '9', '8', '7'], score: 43, innerTens: 1, isPractice: false },
      { name: '7. serie', timeLimit: 20, shots: ['10', '9', '8', '8', '8'], score: 43, innerTens: 0, isPractice: false },
      { name: '8. serie', timeLimit: 20, shots: ['9', '9', '8', '8', '8'], score: 42, innerTens: 0, isPractice: false },
      { name: '9. serie', timeLimit: 10, shots: ['9', '9', '8', '7', '6'], score: 39, innerTens: 0, isPractice: false },
      { name: '10. serie', timeLimit: 10, shots: ['X', '9', '8', '8', '6'], score: 41, innerTens: 1, isPractice: false },
      { name: '11. serie', timeLimit: 10, shots: ['10', '9', '8', '8', '7'], score: 42, innerTens: 0, isPractice: false },
      { name: '12. serie', timeLimit: 10, shots: ['9', '8', '8', '7', '7'], score: 39, innerTens: 0, isPractice: false },
    ],
    totalScore: 518,
    innerTensCount: 4,
  },
  {
    id: 'r6',
    date: '2026-05-20T11:30:00.000Z',
    programType: ProgramType.Standardpistol,
    weaponId: 'w3',
    weaponLabel: 'Sig Sauer P210 Super Target',
    seriesCount: 12,
    series: [
      { name: '1. serie', timeLimit: 150, shots: ['X', 'X', '10', '9', '9'], score: 48, innerTens: 2, isPractice: false },
      { name: '2. serie', timeLimit: 150, shots: ['10', '9', '9', '9', '9'], score: 46, innerTens: 0, isPractice: false },
      { name: '3. serie', timeLimit: 150, shots: ['X', '10', '9', '9', '9'], score: 47, innerTens: 1, isPractice: false },
      { name: '4. serie', timeLimit: 150, shots: ['10', '10', '9', '9', '9'], score: 47, innerTens: 0, isPractice: false },
      { name: '5. serie', timeLimit: 20, shots: ['10', '9', '9', '8', '8'], score: 44, innerTens: 0, isPractice: false },
      { name: '6. serie', timeLimit: 20, shots: ['X', '9', '9', '9', '8'], score: 45, innerTens: 1, isPractice: false },
      { name: '7. serie', timeLimit: 20, shots: ['X', '10', '9', '8', '8'], score: 45, innerTens: 1, isPractice: false },
      { name: '8. serie', timeLimit: 20, shots: ['9', '9', '9', '8', '8'], score: 43, innerTens: 0, isPractice: false },
      { name: '9. serie', timeLimit: 10, shots: ['X', '9', '9', '8', '7'], score: 43, innerTens: 1, isPractice: false },
      { name: '10. serie', timeLimit: 10, shots: ['10', '9', '8', '8', '7'], score: 42, innerTens: 0, isPractice: false },
      { name: '11. serie', timeLimit: 10, shots: ['10', '10', '9', '8', '7'], score: 44, innerTens: 0, isPractice: false },
      { name: '12. serie', timeLimit: 10, shots: ['9', '9', '8', '8', '7'], score: 41, innerTens: 0, isPractice: false },
    ],
    totalScore: 535,
    innerTensCount: 5,
  },
  {
    id: 'r7',
    date: '2026-06-10T16:00:00.000Z',
    programType: ProgramType.T96,
    weaponId: 'w2',
    weaponLabel: 'Glock 17 Gen 5 MOS',
    seriesCount: 16,
    series: [
      { name: '1. serie', timeLimit: 150, shots: ['9', '9', '8', '7', '6'], score: 39, innerTens: 0, isPractice: false, distance: '11 meter', stance: 'stående fri' },
      { name: '2. serie', timeLimit: 150, shots: ['10', '9', '8', '7', '5'], score: 39, innerTens: 0, isPractice: false, distance: '11 meter', stance: 'stående 1 hånd' },
      { name: '3. serie', timeLimit: 20, shots: ['X', '9', '9', '8', '7'], score: 43, innerTens: 1, isPractice: false, distance: '11 meter', stance: 'stående fri' },
      { name: '4. serie', timeLimit: 20, shots: ['9', '8', '8', '6', '5'], score: 36, innerTens: 0, isPractice: false, distance: '11 meter', stance: 'stående 1 hånd' },
      { name: '5. serie', timeLimit: 10, shots: ['X', '10', '9', '8', '6'], score: 43, innerTens: 1, isPractice: false, distance: '11 meter', stance: 'stående fri' },
      { name: '6. serie', timeLimit: 10, shots: ['9', '8', '7', '7', '5'], score: 36, innerTens: 0, isPractice: false, distance: '11 meter', stance: 'stående 1 hånd' },
      { name: '7. serie', timeLimit: 150, shots: ['10', '9', '9', '8', '7'], score: 43, innerTens: 0, isPractice: false, distance: '15 meter', stance: 'stående fri' },
      { name: '8. serie', timeLimit: 150, shots: ['9', '8', '8', '7', '6'], score: 38, innerTens: 0, isPractice: false, distance: '15 meter', stance: 'stående 1 hånd' },
      { name: '9. serie', timeLimit: 20, shots: ['X', '9', '9', '8', '7'], score: 43, innerTens: 1, isPractice: false, distance: '15 meter', stance: 'stående fri' },
      { name: '10. serie', timeLimit: 20, shots: ['9', '8', '7', '7', '6'], score: 37, innerTens: 0, isPractice: false, distance: '15 meter', stance: 'stående 1 hånd' },
      { name: '11. serie', timeLimit: 10, shots: ['10', '9', '8', '8', '7'], score: 42, innerTens: 0, isPractice: false, distance: '15 meter', stance: 'stående fri' },
      { name: '12. serie', timeLimit: 10, shots: ['9', '8', '7', '6', '5'], score: 35, innerTens: 0, isPractice: false, distance: '15 meter', stance: 'stående 1 hånd' },
      { name: '13. serie', timeLimit: 150, shots: ['10', '9', '9', '8', '7'], score: 43, innerTens: 0, isPractice: false, distance: '25 meter', stance: 'stående fri' },
      { name: '14. serie', timeLimit: 150, shots: ['9', '9', '8', '8', '6'], score: 40, innerTens: 0, isPractice: false, distance: '25 meter', stance: 'stående fri' },
      { name: '15. serie', timeLimit: 20, shots: ['X', '10', '9', '8', '7'], score: 44, innerTens: 1, isPractice: false, distance: '25 meter', stance: 'stående fri' },
      { name: '16. serie', timeLimit: 20, shots: ['9', '9', '8', '7', '7'], score: 40, innerTens: 0, isPractice: false, distance: '25 meter', stance: 'stående fri' },
    ],
    totalScore: 633,
    innerTensCount: 4,
  },
];
